// <auto-generated />
using System;
using GearGauge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearGauge.Migrations
{
    [DbContext(typeof(MusicItemDbContext))]
    [Migration("20240702171319_AnotherMigration2")]
    partial class AnotherMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GearGauge.Models.MusicItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("MarketValue")
                        .HasColumnType("int");

                    b.Property<int?>("MusicItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MusicItemId");

                    b.ToTable("MusicItems");
                });

            modelBuilder.Entity("GearGauge.Models.MusicItem", b =>
                {
                    b.HasOne("GearGauge.Models.MusicItem", null)
                        .WithMany("MusicItems")
                        .HasForeignKey("MusicItemId");
                });

            modelBuilder.Entity("GearGauge.Models.MusicItem", b =>
                {
                    b.Navigation("MusicItems");
                });
#pragma warning restore 612, 618
        }
    }
}
